<a href="https://colab.research.google.com/github/SreejithJP/intership/blob/main/prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
data=pd.read_csv('weatherAUS.csv');

In [ ]:
x=data.iloc[:,[1,2,3,4,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21]].values
y=data.iloc[:,-1].values; #slicing=2d

In [ ]:
y=y.reshape(-1,1) #1d to 2d

In [ ]:
from sklearn.impute import SimpleImputer
Imputer=SimpleImputer(missing_values=np.nan,strategy='most_frequent')
x=Imputer.fit_transform(x)
y=Imputer.fit_transform(y)

In [ ]:
#labeling encoding
from sklearn.preprocessing import LabelEncoder
le1=LabelEncoder()
x[:,0] =le1.fit_transform(x[:,0])
le2=LabelEncoder()
x[:,4]=le2.fit_transform(x[:,4])
le3=LabelEncoder()
x[:,6]=le3.fit_transform(x[:,6])
le4=LabelEncoder()
x[:,7]=le4.fit_transform(x[:,7])
le5=LabelEncoder()
x[:,-1]=le5.fit_transform(x[:,-1])
le6=LabelEncoder()
y=le6.fit_transform(y)

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_label.py:116: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [ ]:
#feature scaling
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x=sc.fit_transform(x)


In [ ]:
#splitting the data
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)


In [ ]:
#training model
from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier(n_estimators=100,random_state=0)
classifier.fit(x_train,y_train)

RandomForestClassifier(random_state=0)

In [ ]:
classifier.score(x_train,y_train)

0.9999312525780283

In [ ]:
y_pred=classifier.predict(x_test)

In [ ]:
print(y_pred)

[0 0 0 ... 0 0 0]


In [ ]:
y_pred=le6.inverse_transform(y_pred)

In [ ]:
print(y_pred)

['No' 'No' 'No' ... 'No' 'No' 'No']


In [ ]:
print(y_test)

[1 1 0 ... 1 0 0]


In [ ]:
y_test=le6.inverse_transform(y_test)

In [ ]:
print(y_test)

['Yes' 'Yes' 'No' ... 'Yes' 'No' 'No']


In [ ]:
y_test=y_test.reshape(-1,1)
y_pred=y_pred.reshape(-1,1)

In [ ]:
df=np.concatenate((y_test,y_pred),axis=1)#vertical concat
dataframe=pd.DataFrame(df,columns=['Rain Tommorow','Prediction'])

In [ ]:
print(dataframe)

      Rain Tommorow Prediction
0               Yes         No
1               Yes         No
2                No         No
3                No        Yes
4                No         No
...             ...        ...
29087            No        Yes
29088            No         No
29089           Yes         No
29090            No         No
29091            No         No

[29092 rows x 2 columns]


In [ ]:
#accuracy
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.8521930427608965

In [ ]:
# Import necessary libraries
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.preprocessing import LabelEncoder

# Load dataset
data = pd.read_csv("weatherAUS.csv")

# Data preprocessing
# Handle missing values
data.dropna(inplace=True)

# Encode categorical variables
encoder = LabelEncoder()
data['RainToday'] = encoder.fit_transform(data['RainToday'])
data['RainTomorrow'] = encoder.fit_transform(data['RainTomorrow'])

# Split data into features and target variable
X = data.drop(columns=['RainTomorrow'])
y = data['RainTomorrow']

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Exclude non-numeric columns
numeric_cols = X_train.select_dtypes(include=['float64', 'int64']).columns
X_train_numeric = X_train[numeric_cols]

# Initialize and train the RandomForestClassifier
clf = RandomForestClassifier()
clf.fit(X_train_numeric, y_train)

# Make predictions
X_test_numeric = X_test[numeric_cols]
y_pred = clf.predict(X_test_numeric)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)
print("Classification Report:")
print(classification_report(y_test, y_pred))
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))


Accuracy: 0.8643211627082594
Classification Report:
              precision    recall  f1-score   support

           0       0.88      0.96      0.92      8799
           1       0.78      0.54      0.64      2485

    accuracy                           0.86     11284
   macro avg       0.83      0.75      0.78     11284
weighted avg       0.86      0.86      0.85     11284

Confusion Matrix:
[[8420  379]
 [1152 1333]]


In [ ]:
import joblib

# Save the trained model to a file
joblib.dump(clf, 'random_forest_model.pkl')


['random_forest_model.pkl']

In [ ]:
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder

# Load the trained model
# Replace 'your_model.pkl' with the filename/path where your trained model is saved
# Example: clf = joblib.load('trained_model.pkl')
clf = RandomForestClassifier()
# Load the saved model from file
loaded_model = joblib.load('random_forest_model.pkl')


# Function to prompt user for input
def prompt_user_for_data():
    # Prompt user to enter values for each attribute
    attributes = ['MinTemp', 'MaxTemp', 'Rainfall',
                  'WindGustDir', 'WindGustSpeed', 'WindDir9am', 'WindDir3pm',
                  'WindSpeed9am', 'WindSpeed3pm', 'Humidity9am', 'Humidity3pm',
                  'Pressure9am', 'Pressure3pm', 'Cloud9am', 'Cloud3pm',
                  'Temp9am', 'Temp3pm', 'RainToday']

    user_data = {}
    for attr in attributes:
        user_data[attr] = input(f"Enter value for {attr}: ")

    return user_data

# Function to preprocess user input
def preprocess_user_input(user_data, encoder):
    # Convert categorical variables to numerical using label encoding
    user_data['WindGustDir'] = encoder.transform([user_data['WindGustDir']])[0]
    user_data['WindDir9am'] = encoder.transform([user_data['WindDir9am']])[0]
    user_data['WindDir3pm'] = encoder.transform([user_data['WindDir3pm']])[0]
    user_data['RainToday'] = encoder.transform([user_data['RainToday']])[0]

    # Convert all values to float
    for attr in user_data:
        user_data[attr] = float(user_data[attr])

    return user_data

# Prompt user for input
print("Please enter weather data:")
user_input = prompt_user_for_data()

# Preprocess user input
processed_input = preprocess_user_input(user_input, encoder)  # Pass the encoder instance

# Convert input data to DataFrame
input_df = pd.DataFrame([processed_input])

# Make prediction
prediction = clf.predict(input_df)

# Interpret prediction
if prediction[0] == 0:
    print("Prediction: It will not rain tomorrow.")
else:
    print("Prediction: It will rain tomorrow.")


Please enter weather data:
Enter value for MinTemp: 13.4
Enter value for MaxTemp: 22.9
Enter value for Rainfall: 0.6
Enter value for WindGustDir: W
Enter value for WindGustSpeed: 44
Enter value for WindDir9am: W
Enter value for WindDir3pm: WNW
Enter value for WindSpeed9am: 20
Enter value for WindSpeed3pm: 24
Enter value for Humidity9am: 71
Enter value for Humidity3pm: 22
Enter value for Pressure9am: 1007.7
Enter value for Pressure3pm: 1007.1
Enter value for Cloud9am: 8
Enter value for Cloud3pm: NA
Enter value for Temp9am: 16.9
Enter value for Temp3pm: 21.8
Enter value for RainToday: No


ValueError: y contains previously unseen labels: 'W'